baseURL = 'https://franklinclawdbot.github.io/websites/gavinrouse'
languageCode = 'en-us'
title = 'Gavin Rouse'
theme = 'PaperMod'

[params]
  author = 'Gavin Rouse'
  description = 'Product Quality Test Lead at Cadwell. Modern Renaissance Man. Software quality, political operations, videography. Based in Pasco, Washington.'
  keywords = ['Gavin Rouse', 'developer', 'politics', 'automation', 'Franklin County GOP']
  defaultTheme = 'auto'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.profileMode]
    enabled = true
    title = 'Gavin Rouse'
    subtitle = 'Engineer by trade. Always learning. Always building. Forever free.'
    imageUrl = ''
    imageTitle = ''
    imageWidth = 150
    imageHeight = 150
    
    [[params.profileMode.buttons]]
      name = 'About'
      url = './about/'
    [[params.profileMode.buttons]]
      name = 'Projects'
      url = './projects/'
    [[params.profileMode.buttons]]
      name = 'Now'
      url = './now/'

  [params.homeInfoParams]
    Title = "Hi, I'm Gavin"
    Content = 'I build systems, run political operations, and automate everything that can be automated. Currently focused on treasurer automation, event coordination, and one-man businesses powered by AI.'

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/gavinrouse'
  [[params.socialIcons]]
    name = 'twitter'
    url = 'https://twitter.com/gavinrouse'
  [[params.socialIcons]]
    name = 'email'
    url = 'mailto:gavin@gavinrouse.com'
  [[params.socialIcons]]
    name = 'youtube'
    url = 'https://www.youtube.com/@gavinrouse'
  [[params.socialIcons]]
    name = 'instagram'
    url = 'https://instagram.com/_gavin_rouse_'
  [[params.socialIcons]]
    name = 'rss'
    url = 'index.xml'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 10
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    weight = 20
  [[menu.main]]
    identifier = 'now'
    name = 'Now'
    url = '/now/'
    weight = 30
  [[menu.main]]
    identifier = 'archive'
    name = 'Archive'
    url = '/archives/'
    weight = 40

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNos = true
  style = 'monokai'
