baseURL = 'https://franklinclawdbot.github.io/websites/homedefensespears'
languageCode = 'en-us'
title = 'Home Defense Spears'
theme = 'PaperMod'

[params]
  author = 'Home Defense Spears'
  description = 'Real spears for home defense. Medieval design, modern effectiveness. Shop Cold Steel Assegai and Boar Spears.'
  keywords = ['home security', 'home defense', 'spear', 'cold steel', 'assegai', 'medieval defense']
  defaultTheme = 'auto'
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = false

  [params.profileMode]
    enabled = false
  
  [params.homeInfoParams]
    Title = "Home Defense Spears"
    Content = ""

  [[params.socialIcons]]
    name = 'twitter'
    url = 'https://twitter.com/homedefensespears'
  [[params.socialIcons]]
    name = 'rss'
    url = 'index.xml'

[menu]
  [[menu.main]]
    identifier = 'shop'
    name = 'Shop'
    url = '/spears/'
    weight = 10
  [[menu.main]]
    identifier = 'why'
    name = 'Why Spears?'
    url = '/why-spears/'
    weight = 20
  [[menu.main]]
    identifier = 'articles'
    name = 'Guide'
    url = '/articles/'
    weight = 30
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 40

# Affiliate disclosure
[params.footer]
  customText = "This site contains affiliate links. We may earn a commission if you purchase through these links, at no extra cost to you."
